[project]
name = "wherewasi"
version = "0.1.0"
authors= [ {"name"="Laween Al-Sulaivany", "email"="laweenhamza@gmail.com"},]
description = "A tiny CLI tool that remembers where you left off."
readme = "README.md"

[project.urls]
repository = "https://github.com/laween-alsulaivany/wherewasi"

[build-system]
requires-python = ">=3.14"


dependencies = [
    "click>=8.5.0",
    "rich>=15.0.0",
    "click-default-group>=1.2.4",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I", "B"]


[project.scripts]
wherewasi = "main:cli"
